openapi: 3.2.0
info:
  title: Public Imprint Offers API
  version: '2.0'
servers:
- url: https://dev.sbx.imprint.co
  description: Imprint public api sandbox
security:
- basicAuth: []
- bearerAuth: []
tags:
- name: Offers
paths:
  /v2/offers:
    get:
      tags:
      - Offers
      summary: Retrieve an offer
      x-excluded: true
      operationId: getOffer
      description: Returns the marketing placement for the given customer
      parameters:
      - name: partner_customer_id
        in: query
        schema:
          type: string
          description: The unique identifier for the customer in the partner's system
      responses:
        '200':
          description: Successfully returned marketing placement
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offer'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerCustomerNotFoundError'
components:
  schemas:
    Offer:
      type: object
      description: Offer marketing placement returned for a partner customer
      required:
      - id
      - is_prescreened
      - title
      - description
      properties:
        id:
          type: string
          description: The unique ID Imprint assigns to the offer placement
          example: 2ade1a36-b6f7-489b-a941-865c33f82f5a
        is_prescreened:
          type: boolean
          description: Indicates whether the offer is a prescreened offer
          example: true
        title:
          type: string
          description: Short, human-readable title for the offer
          example: 'Welcome Offer: Earn $25'
        description:
          type: string
          description: Full marketing copy for the offer
          example: Sign-up, accept your offer, and spend $500 in the first 90 days of becoming a cardholder to unlock your $25 welcome bonus. To qualify for the $25 bonus, you must make qualifying purchases totaling $500 or more using your Company® Card within 90 days of account approval.
    PartnerCustomerNotFoundError:
      type: object
      required:
      - type
      - message
      properties:
        type:
          type: string
          description: The category of error being returned
          example: PARTNER_CUSTOMER_NOT_FOUND_ERROR
        message:
          type: string
          description: A message describing the cause of the error
          example: 'Partner Customer not found for provided ID: abcd-efgh-123'
        param:
          type: string
          description: The param causing the error
          example: partner_customer_id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: 'Basic HTTP authentication. Allowed headers-- Authorization: Basic <base64(api_key_id:api_key_secret)>'
    bearerAuth:
      bearerFormat: auth-scheme
      description: 'Bearer HTTP authentication. Allowed headers-- Authorization: Bearer <api_key>'
      scheme: bearer
      type: http
